---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  
  vars_files:
    - /var/lib/jenkins/workspace/ansible-client/ansible-role/install/vars/main.yml
  roles:
    - { role: install }
