- name: download tomcat server packages
  get_url:
    url: "{{ tomcat_url }}"
    dest: /opt
    
- name: extract tomcat packages
  unarchive:
    src: /opt/{{ tomcat_tar }}
    dest: /opt
    remote_src: yes

- name: start tomcat services
  shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh
